//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_system.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appeal()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int IdAppeal { get; set; }
        public string AppealNumber { get; set; }
        public byte IdStatus { get; set; }
        public byte IdCategory { get; set; }
        public int IdClient { get; set; }
        public string BriefDescription { get; set; }
        public string Description { get; set; }
        public string IdAppealForm { get; set; }
        public int IdEmployee { get; set; }
        public byte IdPriority { get; set; }
        public string Commentary { get; set; }
    
        public virtual AppealForm AppealForm { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual Category Category { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
