//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_system.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int IdFeedback { get; set; }
        public byte IdEvaluation { get; set; }
        public string Commentary { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Evaluation Evaluation { get; set; }
    }
}
