//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_system.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int IdTask { get; set; }
        public string TaskNumber { get; set; }
        public byte IdStatus { get; set; }
        public int IdEmployee { get; set; }
        public byte IdPriority { get; set; }
        public string Commentary { get; set; }
        public int IdAppeal { get; set; }
    
        public virtual Appeal Appeal { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
    }
}
